# Generated by Django 3.2.6 on 2021-09-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='upload/profile_photos'),
        ),
    ]
